using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        public int historia = 0;
        public int direita = 0;
        public int esquerda = 1;
        public float MIXER = 0f;
    }
}